### ISSUE TITLE
Add build for web

### ISSUE THREAD

**Issue by romanslonov** [mubaidr/vue-electron-template#467]

**Comment by mubaidr** [comment]
Can you please explain what do you mean by "build for web"?

**Comment by romanslonov** [comment]
Web version of app, usually used to launch an application on the internet.

**Comment by mubaidr** [comment]
`npm run pack:renderer` does the same, it build the web version of the app in the `dist` directory. Let me know if that is sufficient for your need? Otherwise I am open to suggestion.

**Comment by PrestonN** [comment]
Hello!  It seemed appropriate to use this issue instead of creating a new one, as this seems very related.

I have been trying to get my Electron project to run on the web while using your boilerplate.  Cloning down a new version from this repo doesn't seem to fix the issue either.  Here are the steps that I'm doing.

1. Clone down the repo
2. `npm install`
3. `npm run pack:renderer`
4. Open `dist/index.html` within a browser

The result is a blank screen where the console shows the following:

```
ReferenceError: process is not defined
ReferenceError: module is not defined
```

A quick search shows that the problem may have to do with the `libraryTarget` within webpack, however I tried every option available and each ended up with similar issues.

Any help on getting this fixed would be much appreciated.

**Comment by mubaidr** [comment]
This template is not really suitable for web pps. Because web pages in electrons have access to nodejs apis (therefore special target in webpack config) otherwise simpliy building for browser will cause issues with nodejs/electron api access. 

If you have  a special case where you don't need to access these api/nodejs just update webpack config here: https://github.com/mubaidr/vue-electron-template/blob/master/_scripts/webpack.renderer.config.js#L145 as browser.

**Comment by PrestonN** [comment]
Changing the parameter like you mentioned doesn't seem to fix the issue, even when I change it within this repo.  I'm trying to build my app with very few Electron specific API's while including fallbacks if it's ran as a web app.  If you have any other suggestions on making this work then it would be greatly appreciated.

**Comment by mubaidr** [comment]
@romanslonov @PrestonN  I have updated template to generate web build too. It will be generated in the `dit/web/` directory.

**Comment by PrestonN** [comment]
This ended up working for me.  Thanks a bunch!  It is very appreciated!

The one thing that I had to change was [this line](https://github.com/mubaidr/vue-electron-template/blob/master/_scripts/webpack.web.config.js#L105) to the following in order for my code to work:

```js
node: {
    __dirname: isDevMode,
    __filename: isDevMode,
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
  },
```

I wouldn't say it's required to be included within this repository but I wanted to put it here in case someone else gets stuck.

Thanks again!
